// Generated using Sourcery 1.8.1 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT
// 💙💙 Autogenerated for saving Beegees time ⏰
// swiftlint:disable all

@testable import FooApp
import Foundation

extension Macbook {
    static func fixtures(
        id: UUID = .init(uuidString: "52ccd1e4-e4b1-4192-9ffe-1d8f9af30d0f")!,
        macOSVersion: Double = 1.0,
        name: String = "Tim Cook",
        warrantyEndsAt: Date = .init(timeIntervalSince1970: 1_893_499_200),
        owner: Person = .fixtures(),
        lightMode: LightMode = .light
    ) -> Macbook {
        return .init(
            id: id,
            macOSVersion: macOSVersion,
            name: name,
            warrantyEndsAt: warrantyEndsAt,
            owner: owner,
            lightMode: lightMode
        )
    }
}
